import type { WizardAnswers, ToolMapping } from "../lib/types.js";
import { TOOL_MAPPINGS } from "../lib/types.js";

type Template = (answers: WizardAnswers) => string;

const toolDescription = (
  answers: WizardAnswers,
  toolName: string,
): string => {
  const lines = [
    `This file is auto-generated by contextforge for ${toolName}.`,
    "Do not edit directly — edit the source files under `knowledge/` instead.",
    "",
    `Project: ${answers.projectName}`,
    "",
    "Refer to the shared knowledge base for authoritative context:",
    `- knowledge/project-context.md`,
    `- knowledge/architecture.md`,
    `- knowledge/coding-guidelines.md`,
    "",
    "### Stack",
    `- Framework: ${answers.framework}`,
  ];

  if (answers.databases.length) {
    lines.push(`- Database(s): ${answers.databases.join(", ")}`);
  }
  if (answers.orms.length) {
    lines.push(`- ORM(s): ${answers.orms.join(", ")}`);
  }
  if (answers.auth !== "None") {
    lines.push(`- Auth: ${answers.auth}`);
  }
  if (answers.infra.length) {
    lines.push(`- Infrastructure: ${answers.infra.join(", ")}`);
  }
  if (answers.ci !== "None") {
    lines.push(`- CI/CD: ${answers.ci}`);
  }

  return lines.join("\n");
};

const knowledgeContext: Template = (a) =>
  [
    "# Project Context",
    "",
    `## Project: ${a.projectName}`,
    "",
    "This file is the single source of truth about this project for AI coding assistants.",
    "",
    "### Tech Stack",
    "",
    `| Category | Choice |`,
    `|----------|--------|`,
    `| Framework | ${a.framework} |`,
    `| Database(s) | ${a.databases.join(", ") || "None"} |`,
    `| ORM(s) | ${a.orms.join(", ") || "None"} |`,
    `| Authentication | ${a.auth} |`,
    `| Infrastructure / IaC | ${a.infra.join(", ") || "None"} |`,
    `| Security Standards | ${a.securityStandards.join(", ") || "None"} |`,
    `| CI/CD | ${a.ci} |`,
    `| Docker | ${a.docker ? "Yes" : "No"} |`,
    "",
  ].join("\n");

const architecture: Template = (a) =>
  [
    "# Architecture",
    "",
    `## ${a.projectName}`,
    "",
    "### Tech Stack",
    `- Framework: ${a.framework}`,
    `- Database: ${a.databases.join(", ") || "None"}`,
    `- ORM: ${a.orms.join(", ") || "None"}`,
    `- Auth: ${a.auth}`,
    `- Infrastructure: ${a.infra.join(", ") || "None"}`,
    `- CI/CD: ${a.ci}`,
    `- Docker: ${a.docker ? "Yes" : "No"}`,
    "",
    "### Key Architectural Decisions",
    "<!-- Record ADRs here -->",
    "",
    "### Data Flow",
    "<!-- Document main data flow paths -->",
    "",
  ].join("\n");

const codingGuidelines: Template = (a) =>
  [
    "# Coding Guidelines",
    "",
    `## ${a.projectName}`,
    "",
    "### Code Style",
    "- Use consistent formatting (Prettier / ESLint / Biome).",
    "- Prefer explicit over implicit.",
    "- Keep functions small and single-purpose.",
    "",
    "### Naming Conventions",
    "- Files: kebab-case, PascalCase for components/classes.",
    "- Variables/functions: camelCase.",
    "- Constants: UPPER_SNAKE_CASE.",
    "- Types/interfaces: PascalCase.",
    "",
    "### Testing",
    "- Write tests alongside implementation code.",
    "- Test behaviour, not implementation details.",
    "",
    "### Error Handling",
    "- Fail fast for programmer mistakes.",
    "- Handle expected errors gracefully.",
    "",
    "### Security",
    "- Validate all user input.",
    "- Never log secrets, tokens, or PII.",
    a.securityStandards.length
      ? `- Follow: ${a.securityStandards.join(", ")}`
      : "",
    "",
  ]
    .filter(Boolean)
    .join("\n");

const engineeringStandards: Template = () =>
  [
    "# Engineering Standards",
    "",
    "### Code Quality",
    "- All code must pass lint and type checks before merging.",
    "- Avoid dead code and debugging artefacts in PRs.",
    "",
    "### Code Review",
    "- Every PR needs at least one approval.",
    "- Verify correctness, test coverage, and convention adherence.",
    "",
    "### Dependencies",
    "- Audit regularly for vulnerabilities.",
    "- Pin exact versions for reproducible builds.",
    "",
  ].join("\n");

const knowledgeBase: Template = (a) =>
  [
    "# Knowledge Base",
    "",
    `## ${a.projectName}`,
    "",
    "Refer to the shared project context files for authoritative information:",
    "- knowledge/project-context.md",
    "- knowledge/architecture.md",
    "- knowledge/coding-guidelines.md",
    "",
    "### Domains",
    "<!-- List key domain concepts -->",
    "",
    "### Common Patterns",
    "<!-- Document recurring patterns -->",
    "",
    "### Glossary",
    "<!-- Project-specific terminology -->",
    "",
  ].join("\n");

const codeReviewer: Template = (a) =>
  [
    "# Code Reviewer",
    "",
    "### Review Checklist",
    "- [ ] Does the code compile / type-check?",
    "- [ ] Are there sufficient tests?",
    "- [ ] Do existing tests still pass?",
    "- [ ] Is the code idiomatic for the stack?",
    "- [ ] Are error paths handled?",
    "- [ ] Any obvious performance concerns?",
    "- [ ] Secrets hardcoded anywhere?",
    "",
    "### Stack-Specific Concerns",
    `- Framework: ${a.framework}`,
    a.databases.length ? `- Database: ${a.databases.join(", ")}` : "",
    a.orms.length ? `- ORM: ${a.orms.join(", ")}` : "",
    `- Auth: ${a.auth}`,
    "",
  ]
    .filter(Boolean)
    .join("\n");

const securityReviewer: Template = (a) =>
  [
    "# Security Reviewer",
    "",
    "### Security Checklist",
    "- [ ] Input validation on all user-facing endpoints?",
    "- [ ] Authentication on every protected route?",
    "- [ ] Authorisation checks (permissions, not just auth)?",
    "- [ ] No secrets in source code / logs?",
    "- [ ] Dependencies checked for CVEs?",
    "- [ ] Injection vectors reviewed?",
    "- [ ] CSRF protection on state-changing operations?",
    "",
    a.securityStandards.length
      ? `### Compliance: ${a.securityStandards.join(", ")}`
      : "",
    `### Auth: ${a.auth}`,
    "",
  ].join("\n");

export interface TemplateFile {
  path: string;
  render: Template;
}

export const TEMPLATES: TemplateFile[] = [
  { path: "knowledge/project-context.md", render: knowledgeContext },
  { path: "knowledge/architecture.md", render: architecture },
  { path: "knowledge/coding-guidelines.md", render: codingGuidelines },
  { path: "skills/engineering-standards.md", render: engineeringStandards },
  { path: "skills/knowledge-base.md", render: knowledgeBase },
  { path: "skills/code-reviewer.md", render: codeReviewer },
  { path: "skills/security-reviewer.md", render: securityReviewer },
];

export function getToolTemplate(tool: ToolMapping, answers: WizardAnswers): string {
  if (tool.id === "continue") {
    const cfg = {
      "//": "Auto-generated by contextforge. Do not edit directly.",
      name: answers.projectName,
      knowledge: {
        projectContext: "knowledge/project-context.md",
        architecture: "knowledge/architecture.md",
        codingGuidelines: "knowledge/coding-guidelines.md",
      },
      stack: {
        framework: answers.framework,
        databases: answers.databases,
        orms: answers.orms,
        auth: answers.auth,
        infra: answers.infra,
        ci: answers.ci,
      },
    };
    return JSON.stringify(cfg, null, 2);
  }
  return toolDescription(answers, tool.name);
}
